SELECT GAME_USERS.ID, nvl(b.COUNT, 0) PURCHASE_COUNT, nvl(b.PRICE, 0) TOTAL_PRICE 
FROM
GAME_USERS,
(SELECT USER_ID, count(*) COUNT, sum(price) PRICE FROM CHARACTERS, PURCHASES WHERE ITEM=NAME GROUP BY USER_ID) b
WHERE GAME_USERS.ID = b.USER_ID(+)
ORDER BY GAME_USERS.ID