-- Programmers Oracle
-- table명, column명 대소문자 구분 X
-- field값은 구분함

-- WHERE NOT 이랑 정렬 조건 2가지 한 번에 적용할 때
WHERE NOT INTAKE_CONDITION='Aged'
ORDER BY NAME ASC, DATETIME DESC

-- WHERE NOT
WHERE PRICE <>100;
WHERE NOT PRICE =100;

-- 상위 n개 값만 가져올 때 ROWNUM 사용
SELECT NAME 
FROM (SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME DESC)
WHERE ROWNUM < 2;

-- Max
SELECT Max(DATETIME) AS 시간 FROM ANIMAL_INS;

-- Count
SELECT Count(*) FROM TABLE;

-- Sum
SELECT Sum(TEMP)
FROM (SELECT '1' AS TEMP FROM ANIMAL_INS)

-- 중복 제거 DISTINCT // IS NOT NULL
SELECT Count(*) as COUNT 
FROM (SELECT DISTINCT NAME FROM ANIMAL_INS WHERE NAME IS NOT NULL)


--GROUP BY 랑 WEHRE절에 조건 2가지 쓰기
--고양이와 개는 몇마리일까?
--GROUP지은 것에 대해서 칼럼을 보여준다.
SELECT * FROM (
SELECT ANIMAL_TYPE, count(*) count FROM ANIMAL_INS WHERE ANIMAL_TYPE = 'Cat' OR ANIMAL_TYPE = 'Dog'  GROUP BY ANIMAL_TYPE
    ) ORDER BY ANIMAL_TYPE;
    
SELECT [GROUP BY 절에 지정된 컬럼1] [GROUP BY별로 집계할 값] 
FROM [테이블 명] 
GROUP BY [ 그룹으로 묶을 컬럼 값 ]
--https://jink1982.tistory.com/63
    
--Having 절은 Group by로 집계된 값 중 where 절 처럼 특정 조건을 추가
SELECT CLASS, SUM(SCORE) 
FROM TBL_REPORT_CARD 
GROUP BY CLASS
HAVING SUM(SCORE) > 150 ;

SELECT * FROM (
SELECT NAME, COUNT(*) COUNT FROM ANIMAL_INS WHERE NAME IS NOT NULL GROUP BY NAME HAVING COUNT(*) >= 2
    ) ORDER BY NAME;
    
    
--DATE 시간 사용법
    
SELECT * FROM (
	SELECT TO_NUMBER(HOUR) HOUR, COUNT(HOUR) COUNT FROM	(
			SELECT TO_CHAR(DATETIME,'HH24') HOUR FROM ANIMAL_OUTS 
		   			) GROUP BY HOUR
    					) WHERE HOUR >=9 AND HOUR <=19 ORDER BY HOUR


-- 24시간
--http://www.gurubee.net/article/61629
SELECT TO_CHAR ( LEVEL ) lv FROM DUAL CONNECT BY LEVEL <= 24

-- JOIN, OUTERJOIN (오라클 vs ANSI)
-- 그리고 24시간 별로 구할때 0인 레코드도 넣는 방법까지

--방법1 // NVL 사용 (칼럼, null일때 대체할 값) // 대체값이 '뒤'에 온다
 SELECT b.HOUR HOUR, nvl(a.COUNT, 0) COUNT 
 FROM
 (SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR, COUNT(TO_CHAR(DATETIME, 'HH24')) COUNT FROM ANIMAL_OUTS GROUP BY TO_CHAR(DATETIME, 'HH24') ) a, 
 (SELECT TO_NUMBER(LEVEL)-1 HOUR FROM DUAL CONNECT BY LEVEL <= 24) b 
 WHERE b.HOUR = a.HOUR(+) 
 ORDER BY HOUR

--방법2 ANSI
SELECT hour, nvl(count, 0) count FROM (
SELECT b.HOUR HOUR, a.COUNT COUNT
FROM 				 (SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR, COUNT(TO_CHAR(DATETIME, 'HH24')) COUNT 
						FROM ANIMAL_OUTS GROUP BY TO_CHAR(DATETIME, 'HH24') ORDER BY HOUR ) a
RIGHT OUTER JOIN 		(SELECT TO_NUMBER(LEVEL)-1 HOUR FROM DUAL CONNECT BY LEVEL <= 24) b
ON      a.HOUR = b.HOUR
ORDER BY hour
)

-- +붙이는 방향에 주의 (더 "짧아서" 확장해야 하는 쪽에 +를 붙이는거다.) // 긴쪽에 붙이는거 아님.


--IN
SELECT *
  FROM TABLE 
 WHERE COLUMN IN ('A' , 'B')

--IN (풀어썻을 경우)
SELECT *
  FROM TABLE 
 WHERE COLUMN  = 'A' 
    OR COLUMN = 'B'

-- NOT IN (풀어썻을 경우)
SELECT *
  FROM TABLE 
 WHERE COLUMN NOT IN ('A' , 'B')
 
SELECT *
  FROM TABLE 
 WHERE COLUMN  <> 'A' 
   AND COLUMN <> 'B'

-- NOT IN 문제 답
SELECT ANIMAL_ID, NAME FROM ANIMAL_OUTS WHERE ANIMAL_ID 
NOT IN 		(SELECT ANIMAL_ID FROM ANIMAL_INS) 
ORDER BY ANIMAL_ID


-- JOIN (+) 방향 헷갈려서 한참 헤맸던 문제
SELECT * FROM (
SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME
FROM ANIMAL_INS, ANIMAL_OUTS
WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID(+)
AND ANIMAL_INS.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY ANIMAL_INS.DATETIME
) WHERE ROWNUM <=3;

-- LIKE 문자 포함 검색
--출처: https://devjhs.tistory.com/81 [키보드와 하루]
WHERE 컬럼 [NOT] LIKE (%) 검색할 값 ( _ , % ) 

SELECT * 
FROM TEST_TABLE_ONE
WHERE TEL LIKE '010%'


SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.ANIMAL_TYPE, ANIMAL_OUTS.NAME
FROM ANIMAL_INS, ANIMAL_OUTS
WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
AND ANIMAL_INS.SEX_UPON_INTAKE LIKE 'Intact%'
AND ANIMAL_OUTS.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY ANIMAL_OUTS.ANIMAL_ID

-- WHERE안에 AND조건과 OR조건이 혼합되어 있을 때 // LIKE 사용
SELECT * FROM (
	SELECT ANIMAL_ID, NAME
	FROM ANIMAL_INS
	WHERE ANIMAL_TYPE = 'Dog' )
WHERE NAME LIKE '%el%'
OR NAME LIKE 'El%'
ORDER BY NAME


-- SELECT문에서 컬럼의 내용에 따라 다른값으로 출력하기
-- https://breadshuttle.tistory.com/entry/Oracle-SELECT%EB%AC%B8%EC%97%90%EC%84%9C-%EC%BB%AC%EB%9F%BC%EC%9D%98-%EB%82%B4%EC%9A%A9%EC%97%90-%EB%94%B0%EB%9D%BC-%EB%8B%A4%EB%A5%B8%EA%B0%92%EC%9C%BC%EB%A1%9C-%EC%B6%9C%EB%A0%A5%ED%95%98%EA%B8%B0

-- DECODE : https://gent.tistory.com/227

-- Decode는 like검색을 할 수 없다 하려면 case문으로
--출처: https://ghstylus.tistory.com/17 [개발을 해보자]
하지만 case when raw like '%법' then ' '||'1' else '2' || 이걸로 가능
-- CASE로 풀기
SELECT ANIMAL_ID, NAME,
    CASE
        WHEN SEX_UPON_INTAKE LIKE '%Neutered%' THEN 'O'
        WHEN SEX_UPON_INTAKE LIKE '%Spayed%' THEN 'O'
        ELSE 'X'
    END AS 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

-- DECODE로 풀기	
SELECT ANIMAL_ID, NAME,
    DECODE(SEX_UPON_INTAKE, 'Neutered Male', 'O', 'Spayed Female', 'O', 'X') AS 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

-- 보호기간 길었던 동물 2마리
SELECT ANIMAL_ID, NAME FROM (
SELECT ANIMAL_INS.ANIMAL_ID ANIMAL_ID, ANIMAL_INS.NAME NAME, ANIMAL_OUTS.DATETIME-ANIMAL_INS.DATETIME STAYTIME
FROM ANIMAL_INS, ANIMAL_OUTS
WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
ORDER BY STAYTIME DESC --Alias로도 해당 Select문에 정렬 적용 가능
) WHERE ROWNUM<3

-- DATETIME 형변환
SELECT ANIMAL_ID, NAME, TO_CHAR(DATETIME, 'YYYY-MM-DD') 날짜
FROM ANIMAL_INS
ORDER BY ANIMAL_ID